kind: Deployment
apiVersion: apps/v1
metadata:
# set your lab user name
  name: user11-hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
# set your lab user name
      app: user11-hello-world
  template:
    metadata:
      labels:
# set your lab user name
        app: user11-hello-world
    spec:
      volumes:
        - name: index-html
          configMap:
            name: '{{ .Chart.Name }}-html'
            defaultMode: 420
      containers:
        volumeMounts:
          - name: index-html
            mountPath: /tmp/html # this will mount the html.index file to it application location
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: hello-world
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
# Update with the image you build in part 1
          image: 'quay.io/daniel_shani/hello_world:v2'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10